---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    class: coloredlogs.ColoredFormatter
    format: "[%(asctime)s] - [%(levelname)s] - [%(name)s] - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

loggers:
  es:
    level: DEBUG
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console]